version: "3"
services:
  otter_manager:
    image: ${DOCKER_REGISTRY-}otter_manager
    build:
      context: .
      dockerfile: otter_manager/Dockerfile
    restart: always
    container_name: otter_manager
    hostname: otter_manager
    networks:
      otter:
        ipv4_address: 10.21.0.10
    ports:
      - 8080:8080 
      - 8018:8018 #zookeeper ui
      - 33061:3306 
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      ZOO_CLUSTER: otter_manager:2181,node01:2181,node02:2181
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=otter_manager:2888:3888 server.2=node01:2888:3888 server.3=node02:2888:3888
    extra_hosts:
      - "otter_manager:10.21.0.10"
      - "node01:10.21.0.11"      
      - "node02:10.21.0.12"

  node01:
    image: ${DOCKER_REGISTRY-}otter_node
    build:
      context: .
      dockerfile: otter_node/Dockerfile
    restart: always
    container_name: node01
    hostname: node01
    networks:
      otter:
        ipv4_address: 10.21.0.11
    ports:
      - 33062:3306 
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      ZOO_CLUSTER: otter_manager:2181,node01:2181,node02:2181
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=otter_manager:2888:3888 server.2=node01:2888:3888 server.3=node02:2888:3888
    extra_hosts:
      - "otter_manager:10.21.0.10"
      - "node01:10.21.0.11"      
      - "node02:10.21.0.12" 
    depends_on:
      - otter_manager

  node02:
    image: ${DOCKER_REGISTRY-}otter_node
    build:
      context: .
      dockerfile: otter_node/Dockerfile
    restart: always
    container_name: node02
    hostname: node02
    networks:
      otter:
        ipv4_address: 10.21.0.12
    ports:
      - 33063:3306 
    environment:
      TZ: Europe/Rome #Asia/Shanghai 时区
      ZOO_CLUSTER: otter_manager:2181,node01:2181,node02:2181
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=otter_manager:2888:3888 server.2=node01:2888:3888 server.3=node02:2888:3888
    extra_hosts:
      - "otter_manager:10.21.0.10"
      - "node01:10.21.0.11"      
      - "node02:10.21.0.12"
    depends_on:
      - node01

networks:
  otter:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0/16
          gateway: 10.21.0.1